name: Node CI

on:
  pull_request:
    branches: [master]

jobs:
  test_pr:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: pip install faker sqlite3
      - run: python build_mock_db.py
      - run: npm ci
      - run: npm test
      - run: npm run build
